### PR TITLE
PowerShell environment script

### PR DESCRIPTION
**Pull request by erwanregy**
A PowerShell script equivalent of the environment.bat Command Prompt script

This would be useful for users who primarily use PowerShell.

### CODE REVIEW

**Comment by erwanregy** [comment]
If approved, I note that the README should probably also be updated to add instructions for PowerShell users

**Comment by mmicko** [comment]
Thanks for PR. Will need to check this, but may take some time, since Windows is not my main dev environment. No worries about two PRs :) all fine

**Comment by mmicko** [comment]
OK PR is missing a glue logic to actually add this to release, but that is not issue for me to add.  Was testing this on Windows 10.
Main issue, by my opinion, is that running scripts are not automatically possible unless you enable that on your machine, which requires allowing "unrestricted" script execution in worst case, and lowering security levels of your own machine is something that we would not wish to promote.
Also running `.\start.bat` directly from powershell works just nice without any change.

**Comment by mmicko** [comment]
Closing as not in scope

**Pull request closed without merging**
