### PR TITLE
Added nextpnr-himbaechel

### PR DESCRIPTION
**Pull request by lushaylabs**
Added nextpnr himbaechel for Gowin chips

### CODE REVIEW

**Comment by lushaylabs** [comment]
There is an issue on windows where nextpnr-himbaechel is by default searching for the chibdb under:
<bin_dir>/../share/himbaechel/gowin/chipdb-GW1N-1.bin instead of <bin_dir>/share/nextpnr/himbaechel/gowin/chipdb-GW1N-1.bin (with the added nextpnr directory) 
on MacOs this works fine still debugging this

as a workaround the path can be manually set using --chipdb

**Comment by lushaylabs** [comment]
The issue ended up being in nextpnr so I opened a PR there https://github.com/YosysHQ/nextpnr/pull/1314 

So this PR is good to go from my side

**Comment by lushaylabs** [comment]
hi @mmicko this is my first time contributing to this repo, is there anything I should do for this pr? like add a reviewer or something like that

**Comment by mmicko** [comment]
Sorry @lushaylabs just was too busy. Will take care of this PR.

**Comment by lushaylabs** [comment]
no worries, and thank you, just wanted to check to make sure I wasn't missing something from my end

**Comment by mmicko** [comment]
@lushaylabs Sorry was bit busy today, but there are couple of things wrong. You create chipdb files using pip installed apycula and not one from build (that can potentially be different), also you depend on apicula-bba which is not used at all.  Himbaechel build should be just binary, and independent of architecture, only chip databases should be built as separate packages as native (so once built since that is just data no code).
If you do not mind I would take care of these changes. Idea is to be easy later to add new architecture.

**Comment by mmicko** [comment]
I guess I should force flat install since apycula does not work when in egg

**Comment by lushaylabs** [comment]
I used the pip version of apycula, the previous version (nextpnr-gowin) had an option to accept a precalculated bba file so this wasn't needed. It would pull the bba export and build nextpnr. nextpnr-himbaechel doesn't have this option so I had to add the 'python3-native' dependency and install the pip version as a pre-step `scripts/nextpnr-himbaechel.sh`

**Comment by mmicko** [comment]
A have merged your changes and added changes I mentioned above. Please do try it in your setup and ping me with results.  Sorry I did not took a look at this one before.

**Pull request merged**
